routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\User;
use App\Article;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $slide = Article::where('status','publish')->limit(3)->get();
    $content = Article::where('status','publish')->inRandomOrder()->limit(6)->get();
    return view('blog',['slide' => $slide, 'content' => $content,'menu' => 'home']);
});

Auth::routes();

Route::get('/single/{slug}', 'PostController@show')->name('single');
Route::get('/article', function(){
    $content = Article::where('status','publish')->paginate(9);
    return view('article',['content' => $content,'menu' => 'articles']);
});

Route::group(['prefix' => '/admin', 'middleware' => 'auth'], function () {
    //dashboard
    Route::get('/', function(){
        $name = User::where('id', Auth::id())->first()->name;
        $counUser = count(User::get());
        $counArticle = count(Article::get());
        $counArticleDraft = count(Article::where('status','draf')->get());
        $counArticleTrash = count(Article::onlyTrashed()->get());
        return view('admin.dashboard',['menu' => 'dashboard', 'submenu' => 'dashboard', 'name' => $name, 
        'article' => $counArticle, 'user' => $counUser, 'draft' => $counArticleDraft, 'trash' => $counArticleTrash]);
    });
    Route::get('/dashboard', function(){
        $name = User::where('id', Auth::id())->first()->name;
        $counUser = count(User::get());
        $counArticle = count(Article::get());
        $counArticleDraft = count(Article::where('status','draf')->get());
        $counArticleTrash = count(Article::onlyTrashed()->get());
        return view('admin.dashboard',['menu' => 'dashboard', 'submenu' => 'dashboard', 'name' => $name, 
        'article' => $counArticle, 'user' => $counUser, 'draft' => $counArticleDraft, 'trash' => $counArticleTrash]);
    })->name('dashboard');
    
    //post
    Route::resource('post', 'PostController');
    //category
    Route::get('/category', 'PostController@category')->name('post.category');
    Route::post('/category', 'PostController@storeCategory')->name('post.category.store');
    Route::delete('/category/{id}', 'PostController@destroyCategory')->name('post.category.destroy');
    //trash article
    Route::get('/trash', 'PostController@trash')->name('post.trash');
    Route::put('/trash/{id}', 'PostController@restore')->name('post.trash.restore');
    Route::delete('/trash/{id}', 'PostController@permanentDestroy')->name('post.trash.destroy');

    //user
    Route::resource('users', 'UserController');

    //role
    Route::get('/role', 'RoleController@index')->name('users.role');
    Route::post('/role', 'RoleController@create')->name('users.role.create');
    Route::put('/role', 'RoleController@update')->name('users.role.update');
    Route::delete('/role', 'RoleController@delete')->name('users.role.delete');
});

resources/views/admin/addEditArticle.blade.php
@extends('layouts.admin')

@section('header')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('plugins/bootstrap-tagsinput/css/bootstrap-tagsinput.css') }}">
    <!-- summernote -->
    <link rel="stylesheet" href="{{ asset('plugins/summernote/summernote-bs4.css') }}">
  <style>

.bootstrap-tagsinput {
    background-color: #fff;
    border: 1px solid #ccc;
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
    display: block;
    padding: 4px 6px;
    color: #555;
    vertical-align: middle;
    border-radius: 4px;
    max-width: 100%;
    line-height: 22px;
    cursor: text;
}
.bootstrap-tagsinput input {
    border: none;
    box-shadow: none;
    outline: none;
    background-color: transparent;
    padding: 0 6px;
    margin: 0;
    width: auto;
    max-width: inherit;
}

.thumbnail {
  position: relative;
  width: 769px;
  height: 330px;
  overflow: hidden;
  margin: auto;
  background: #555;
}
.overlays{
  font-size: 100px;
  position: absolute;
  top: 0;
  bottom: 0;
  right: 0;
  left: 0;
  background-color: #ffffffba;
  z-index: 99;
  display: none;
}

.icon-upload{
  color: #949494;
  position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
.thumbnail:hover > .overlays{
  display: inherit;
  cursor: pointer;
}
.thumbnail img {
  position: absolute;
  left: 50%;
  top: 50%;
  height: 100%;
  width: auto;
  -webkit-transform: translate(-50%,-50%);
      -ms-transform: translate(-50%,-50%);
          transform: translate(-50%,-50%);
}
  </style>
@endsection

@section('footer')
  <!-- DataTables -->
  <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
  <script src="{{ asset('plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
  <script src="{{ asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
  <script src="{{ asset('plugins/bootstrap-switch/js/bootstrap-switch.min.js') }}"></script>
  <script src="{{ asset('plugins/bootstrap-tagsinput/js/bootstrap-tagsinput.js') }}"></script>
  <!-- Summernote -->
  <script src="{{ asset('plugins/summernote/summernote-bs4.min.js') }}"></script>

  <script>
    $("input[data-bootstrap-switch]").each(function(){
      $(this).bootstrapSwitch('state', $(this).prop('checked'));
    });

    $('.overlays').click((e)=>{
      $('#img').click();
    })

    $('#img').on('change', function(){
      if (this.files && this.files[0]) { 
         var reader = new FileReader(); 
         reader.onload = function (e) { 
                 $('#thumbnail').attr('src', e.target.result); 
         }
         reader.readAsDataURL(this.files[0]); 
      }
    }) 
    
    $(function () {
      // Summernote
      $('.textarea').summernote({ height: 400})
    })
  </script>
@endsection

@section('content')
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <a href="{{route('post.index')}}" class="btn btn-danger btn-sm"><i class="fas fa-angle-left"></i> Back</a>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          @if ($submenu == 'add article')
            <form action="{{route('post.store')}}" method="post" enctype="multipart/form-data">
          @else
            <form action="{{route('post.update', $data['id'])}}" method="post"  enctype="multipart/form-data">
            {{ method_field('PUT') }}
          @endif
          
            {{ csrf_field() }}
            
            <div class="form-group">
              <label>Title</label>
  
              <div class="input-group">
              <input type="text" class="form-control" name="title" required value="{{ ($submenu == 'edit article' ? $data['title'] : '') }}">
              </div>
              <!-- /.input group -->
            </div>

            <div class="form-group">
              <label>Isi</label>

                <div class="mb-3">
                  <textarea class="textarea" name="isi" placeholder="Place some text here" style="width: 100%; height: 400px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">
                    {{ ($submenu == 'edit article' ? $data['content'] : '') }}
                  </textarea>
                </div>
              
              <!-- /.input group -->
            </div>

            <div class="form-group">
              <label>Category</label>
              <select class="form-control" name="category" style="width: 100%;">
                <option value='0' {{ ($submenu == 'edit article' && $data['category_id'] == 0 ? 'selected' : '') }}>Default</option>
                @foreach ($category as $c)
              <option value="{{$c['id']}}" {{ ($submenu == 'edit article' && $data['category_id'] == $c['id'] ? 'selected' : '') }}>{{$c['category_name']}}</option>
                @endforeach
               </select>
            </div>

            <div class="form-group">
              <label>Tag (tag, tag1, tag2)</label>
              <input type="text" name="tag" data-role="tagsinput" id="tags" class="form-control"  value="{{ ($submenu == 'edit article' ? $data['tag'] : '') }}">
            </div>

            <div class="form-group">
              <label>Status</label>
              <select class="form-control" name="status" style="width: 100%;">
                <option value='draf' {{ ($submenu == 'edit article' && $data['status'] == 'draf' ? 'selected' : '') }}>Draft</option>
                <option value='publish' {{ ($submenu == 'edit article' && $data['status'] == 'publish' ? 'selected' : '') }}>Published</option>
              </select>
            </div>
            {{-- comment --}}
            <div class="form-group">
              <label>Comment</label>
  
              <div class="input-group">
                <input type="checkbox" name="comment" data-bootstrap-switch="" {{ ($submenu == 'edit article' && $data['comment'] == true ? 'checked' : '') }}>
              </div>
              <!-- /.input group -->
            </div>

            <div class="form-group">
              <label>Thumbnail</label>
  
              <div class="input-group">
                <div class="thumbnail">
                  <img src="{{ ($submenu == 'edit article' ? asset('img/'.$data['thumbnail']) : asset('img/thumbnail.jpg')) }}" alt="Image" id="thumbnail" />
                  <input type="file" name="thumbnail" id="img" style="display: none">
                  <div class="overlays">
                     <i class="fas fa-camera icon-upload"></i>
                  </div>
                </div>
              </div>
              <!-- /.input group -->
            </div>
            <button type="submit" name="save" class="btn btn-primary float-sm-right" style="padding-left: 20px; padding-right:20px; ">Save</button>
          </form>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</div>
@endsection

resources/views/admin/addEditUser.blade.php
@extends('layouts.admin')

@section('header')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('plugins/bootstrap-tagsinput/css/bootstrap-tagsinput.css') }}">
    <!-- summernote -->
    <link rel="stylesheet" href="{{ asset('plugins/summernote/summernote-bs4.css') }}">
    <style>
      .hide{
        display: none;
      }
    </style>
@endsection

@section('footer')
  <!-- DataTables -->
  <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
  <script src="{{ asset('plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
  <script src="{{ asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
  <script src="{{ asset('plugins/bootstrap-switch/js/bootstrap-switch.min.js') }}"></script>
  <script src="{{ asset('plugins/bootstrap-tagsinput/js/bootstrap-tagsinput.js') }}"></script>
  <!-- Summernote -->
  <script src="{{ asset('plugins/summernote/summernote-bs4.min.js') }}"></script>

  <script>
    $('#pw').on('input', function(){
      $('.alert-pw').hide();
    })

    $('#repw').on('input', function(){
      $('.alert-pw').hide();
    })

    $('#show').click(function(){
      $('#show').hide()
      $('#foldpw').show();
      $('#fpw').show();
      $('#frepw').show();
      $('#pw').prop('required',true);
      $('#repw').prop('required',true);
      $('#oldpw').prop('required',true);
    })

    function kirim(){
        var pw = $('#pw').val();
        var repw = $('#repw').val();

        if(pw == repw){
          $('#save').click();
        }else{
          $('.alert-pw').show();
        }
    }
  </script>
@endsection

@section('content')
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <a href="{{route('users.index')}}" class="btn btn-danger btn-sm"><i class="fas fa-angle-left"></i> Back</a>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          @if ($submenu == 'add user')
            <form action="{{route('users.store')}}" method="post" enctype="multipart/form-data">
          @else
            <form action="{{route('users.update', $data['id'])}}" method="post"  enctype="multipart/form-data">
            {{ method_field('PUT') }}
          @endif
          
            {{ csrf_field() }}

            <div class="form-group">
              <label>Name</label>
  
              <div class="input-group">
                <input type="text" class="form-control" name="name" required value="{{ ($submenu == 'edit user' ? $data['name'] : '') }}">
              </div>
              <!-- /.input group -->
            </div>

            <div class="form-group">
              <label>Email</label>
  
              <div class="input-group">
                <input type="email" class="form-control" name="email" required value="{{ ($submenu == 'edit user' ? $data['email'] : '') }}">
              </div>
              <!-- /.input group -->
            </div>

            <div class="form-group">
              <label>Role</label>
              <select class="form-control" name="role" style="width: 100%;">
                <option value='0' {{ ($submenu == 'edit user' && $data['role_id'] == 0 ? 'selected' : '') }}>Default</option>
                @foreach ($roles as $r)
              <option value="{{$r['id']}}" {{ ($submenu == 'edit user' && $data['role_id'] == $r['id'] ? 'selected' : '') }}>{{$r['role_name']}}</option>
                @endforeach
              </select>
            </div>
            @if ($submenu == 'edit user')
            <div class="form-group">
              <div class="input-group">
                <button name="show" id="show" type="button" class="btn btn-warning float-sm-right" style="padding-left: 20px; padding-right:20px; ">Edit Password</button>
              </div>
            </div>
            <div class="form-group {{ ($submenu == 'edit user'? 'hide':'' )}}" id="foldpw">
              <label>Old-Password</label>
  
              <div class="input-group">
                <input type="password'" class="form-control" name="oldpassword" {{ ($submenu == 'edit user'? '':'reqired' )}} id="oldpw">
              </div>
            </div>
            @endif
            <div class="form-group {{ ($submenu == 'edit user'? 'hide':'' )}}" id="fpw">
              <label>Password</label>
  
              <div class="input-group">
                <input type="password" class="form-control" name="password" {{ ($submenu == 'edit user'? '':'reqired' )}} id="pw">
                
              </div>
              <div class="text-danger alert-pw hide">Password tidak sama</div>
              <!-- /.input group -->
            </div>
            <div class="form-group {{ ($submenu == 'edit user'? 'hide':'' )}}" id="frepw">
              <label>Re-Password</label>
  
              <div class="input-group">
                <input type="password" class="form-control" name="repassword" {{ ($submenu == 'edit user'? '':'reqired' )}} id="repw">
                
              </div>
              <div class="text-danger alert-pw hide">Password tidak sama</div>
              <!-- /.input group -->
            </div>
            <button type="submit" name="save" style="display: none" class="btn btn-primary float-sm-right" style="padding-left: 20px; padding-right:20px; " id="save"></button>
          
          </form>
          <button  class="btn btn-primary float-sm-right" style="padding-left: 20px; padding-right:20px;" onclick="kirim()">Save</button>
          
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</div>
@endsection

resources/views/admin/articles.blade.php
@extends('layouts.admin')

@section('header')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
@endsection

@section('footer')
  <!-- DataTables -->
  <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
  <script src="{{ asset('plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
  <script src="{{ asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
  
  <script>
    function hapus(url){
      $('#hapus').attr('action', url);
      var id = id;
        Swal.fire({
        title: 'Apa anda yakin?',
        text: "Data ini akan dihapus!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Ya, Yakin!',
        cancelButtonText: 'Batalkan'
      }).then((result) => {
        if (result.value) {
          $('#hapus').submit();
        }
      })
    }

    function restore(url){
        $('#restore').attr('action', url);
        Swal.fire({
        title: 'Apa anda yakin?',
        text: "Data ini akan dikembalikan!",
        icon: 'info',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Ya, Yakin!',
        cancelButtonText: 'Batalkan'
      }).then((result) => {
        if (result.value) {
          $('#restore').submit();
        }
      })
    }

    $(function () {
      $("#example1").DataTable({
        "scrollX": true
      });
    });

  </script>
@endsection

@section('content')
@php

    function cekRole($menu){
      
      $getRole_id = App\User::where('id', Illuminate\Support\Facades\Auth::id())->first()->role_id;
      try{
        $getCode = App\Role::where('id',$getRole_id)->first()->role_code;
      }catch(\Exception $e){
          return str_split("0100", '1');
      }
      

      $getRoleCode = explode('|', $getCode);

      switch ($menu) {
        case 'list article': return str_split($getRoleCode[0], '1'); break;
        case 'category': return str_split($getRoleCode[1], '1'); break;
        case 'trash': return str_split($getRoleCode[2], '1'); break;
        case 'users': return str_split($getRoleCode[3], '1'); break;
        case 'role': return str_split($getRoleCode[4], '1'); break;
      }

    }
@endphp
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          @if ($submenu == 'trash articles')
            <h3 class="card-title">List Trash Article</h3>
          @else
            <h3 class="card-title">List Article</h3>
            @if (cekRole('list article')[0] == "1")
              <a href="{{route('post.create')}}" class="btn btn-primary btn-sm float-sm-right"><i class="fas fa-plus"></i> Add Article</a>
            @endif
          @endif
         </div>
        <!-- /.card-header -->
        <div class="card-body">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>No</th>
              <th>Slug</th>
              <th>Title</th>
              <th>Isi</th>
              <th>Status</th>
              <th>Thumbnail</th>
              <th>Comment</th>
              <th>Category</th>
              <th>Tag</th>
              <th>Author</th>
              <th>Create_at</th>
              <th>Update_at</th>
              <th>Action</th>
            </tr>
            </thead>
            <tbody>
              @php $i = 1 @endphp 
              @foreach ($data as $d)
                <tr>
                  <td>{{ $i++ }}</td>
                  <td>{{$d['slug']}}</td>
                  <td>{{$d['title']}}</td>
                  <td>{{$d['content']}}</td>
                  <td>{{$d['status']}}</td>
                  <td>
                    <img src="{{ asset('img/'.$d['thumbnail'])}}" style="max-width: 100%;height: 70px;">
                  </td>
                  <td>{{ ($d['comment'] == 1? 'True' : 'False') }}</td>
                  <td>
                    @php
                      try {
                          echo App\Category::where('id', $d['category_id'])->first()->category_name;
                      } catch (\Exception $e) {
                          echo "Default";
                      }
                   @endphp
                </td>
                  <td>{{$d['tag']}}</td>
                  <td>
                    @php
                      try {
                          echo App\User::where('id', $d['create_by'])->first()->name;
                      } catch (\Exception $e) {
                          echo "Admin";
                      }
                    @endphp
                  </td>
                  <td>{{$d['created_at']}}</td>
                  <td>{{$d['updated_at']}}</td>
                  <td>
                    @if ($submenu == 'trash articles')
                    {{-- restore --}}
                    @if (cekRole('trash')[2] == "1")
                      <button class="btn btn-primary btn-xs" onclick="restore('{{route('post.trash.restore', $d['id'])}}')">Restore</button>
                    @endif
                    @if (cekRole('trash')[3] == "1")
                      <button class="btn btn-danger btn-xs" onclick="hapus('{{route('post.trash.destroy', $d['id'])}}')">Delete</button>
                    @endif
                    @else
                      @if (cekRole('list article')[2] == "1")
                        <a href="{{ route('post.edit', $d['id'])}}" class="btn btn-success btn-xs">Edit</a>
                      @endif
                      @if (cekRole('list article')[3] == "1")
                        <button class="btn btn-danger btn-xs" onclick="hapus('{{route('post.destroy', $d['id'])}}')">Delete</button>
                      @endif
                    @endif
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>
        <form action="" method="post" id="restore">
          {{ csrf_field() }}
          {{ method_field('PUT') }}
        </form>
        <form action="" method="post" id="hapus">
          {{ csrf_field() }}
          {{ method_field('DELETE') }}
        </form>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</div>
@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <!-- Info boxes -->
    <div class="row">
      <div class="col-12 col-sm-6 col-md-3">
        <div class="info-box">
          <span class="info-box-icon bg-info elevation-1"><i class="fas fa-newspaper"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Articles</span>
            <span class="info-box-number">
              {{$article}}
            </span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
      <div class="col-12 col-sm-6 col-md-3">
        <div class="info-box mb-3">
          <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-list-alt"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Draft Articles</span>
          <span class="info-box-number">{{$draft}}</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->

      <!-- fix for small devices only -->
      <div class="clearfix hidden-md-up"></div>

      <div class="col-12 col-sm-6 col-md-3">
        <div class="info-box mb-3">
          <span class="info-box-icon bg-success elevation-1"><i class="fas fa-trash"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Trash Articles</span>
          <span class="info-box-number">{{$trash}}</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
      <div class="col-12 col-sm-6 col-md-3">
        <div class="info-box mb-3">
          <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-users"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Users</span>
          <span class="info-box-number">{{$user}}</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
    </div>
  </div>
@endsection

resources/views/admin/users.blade.php
@extends('layouts.admin')

@section('header')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
@endsection

@section('footer')
  <!-- DataTables -->
  <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
  <script src="{{ asset('plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
  <script src="{{ asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
  
  <script>
    function hapus(url){
      $('#hapus').attr('action', url);
      var id = id;
        Swal.fire({
        title: 'Apa anda yakin?',
        text: "Data ini akan dihapus!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Ya, Yakin!',
        cancelButtonText: 'Batalkan'
      }).then((result) => {
        if (result.value) {
          $('#hapus').submit();
        }
      })
    }

    function restore(id){
      var id = id;
        Swal.fire({
        title: 'Apa anda yakin?',
        text: "Data ini akan dikembalikan!",
        icon: 'info',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Ya, Yakin!',
        cancelButtonText: 'Batalkan'
      }).then((result) => {
        if (result.value) {
          $('#restore').submit();
        }
      })
    }

    $(function () {
      $("#example1").DataTable({
        "scrollX": true
      });
    });

  </script>
@endsection

@section('content')
@php

    function cekRole($menu){
      
      $getRole_id = App\User::where('id', Illuminate\Support\Facades\Auth::id())->first()->role_id;
      try{
        $getCode = App\Role::where('id',$getRole_id)->first()->role_code;
      }catch(\Exception $e){
          return str_split("0100", '1');
      }
      

      $getRoleCode = explode('|', $getCode);

      switch ($menu) {
        case 'list article': return str_split($getRoleCode[0], '1'); break;
        case 'category': return str_split($getRoleCode[1], '1'); break;
        case 'trash': return str_split($getRoleCode[2], '1'); break;
        case 'users': return str_split($getRoleCode[3], '1'); break;
        case 'role': return str_split($getRoleCode[4], '1'); break;
      }

    }
@endphp

<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
            <h3 class="card-title">List User</h3>
            @if (cekRole('category')[0] == "1")
              <a href="{{route('users.create')}}" class="btn btn-primary btn-sm float-sm-right"><i class="fas fa-plus"></i> Add User</a>
            @endif
          </div>
        <!-- /.card-header -->
        <div class="card-body">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>No</th>
              <th>Nama</th>
              <th>Email</th>
              <th>Password</th>
              <th>Role</th>
              <th>Create_at</th>
              <th>Update_at</th>
              <th>Action</th>
            </tr>
            </thead>
            <tbody>
              @php $i = 1 @endphp 
              @foreach ($data as $d)
                <tr>
                  <td>{{ $i++ }}</td>
                  <td>{{$d['name']}}</td>
                  <td>{{$d['email']}}</td>
                  <td>{{$d['password']}}</td>
                  <td>
                    @php
                      try {
                          echo App\Role::where('id', $d['role_id'])->first()->role_name;
                      } catch (\Exception $e) {
                          echo "Member";
                      }
                   @endphp
                  </td>
                  <td>{{$d['created_at']}}</td>
                  <td>{{$d['updated_at']}}</td>
                  <td>
                    @if (cekRole('category')[2] == "1")
                      <a href="{{ route('users.edit', $d['id'])}}" class="btn btn-success btn-xs">Edit</a>
                    @endif
                    @if (cekRole('category')[3] == "1")
                      <button class="btn btn-danger btn-xs" onclick="hapus('{{route('users.destroy', $d['id'])}}')">Delete</button>
                    @endif
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
          <form action="" method="post" id="hapus">
            {{ csrf_field() }}
            {{ method_field('DELETE') }}
          </form>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</div>
@endsection